import 'package:hive/hive.dart';

part 'bid_model.g.dart'; // Generated by build_runner

@HiveType(typeId: 0)
class Requirement {
  @HiveField(0)
  String name;

  @HiveField(1)
  bool isUploaded;

  Requirement({required this.name, this.isUploaded = false});
}

@HiveType(typeId: 1)
class Bid extends HiveObject {
  @HiveField(0)
  String title;

  @HiveField(1)
  DateTime deadline;

  @HiveField(2)
  List<Requirement> requirements;

  @HiveField(3)
  int reminderMinutesBefore;

  Bid({
    required this.title,
    required this.deadline,
    required this.requirements,
    this.reminderMinutesBefore = 0,
  });

  // Logic to calculate progress for the pie chart
  double get progress {
    if (requirements.isEmpty) return 0.0;
    int completed = requirements.where((req) => req.isUploaded).length;
    return completed / requirements.length;
  }
}
